### ISSUE TITLE
Feedback: Great! Tip: git-restore-mtime 

### ISSUE THREAD

**Issue by marble** [mgeier/sphinx-last-updated-by-git#3]
Cool, exactly what I (we: docs.typo3.org) need right now as well.

We'll be using in in combination with:
https://github.com/MestreLion/git-tools/blob/master/git-restore-mtime

**Comment by mgeier** [comment]
Thanks!

Just out of curiosity: what are you using `git-restore-mtime` for?

**Comment by marble** [comment]
This manual, for example, encompasses thousands of files: https://docs.typo3.org/c/typo3/cms-core/master/en-us/ First time rendering takes more than 30 minutes but only some seconds if Sphinx can use its built in caching mechanism. To make caching work the file modification times (mtimes) must not change.

Git however, by design, doesn't care about file mtimes and doesn't keep them. That's where the mentioned script comes in. It very quickly sets the file modification date to the date of the last change of that file as given by the commit history. After running the script the modification time of each file therefore is its "last update" date.

**Comment by mgeier** [comment]
OK, thanks, good to know!

**Comment by mgeier** [comment]
Do you think it would make sense to mention `git-restore-mtime` in the README (#6)?

**Comment by marble** [comment]
Let me give something back. I studied your solution but came to the conclusion that it's probably not the way to go for me (and the TYPO3 community). Main problem is efficiency, as it takes to many Git calls. Meanwhile I created a specially taylored Sphinx extension [sphinxcontrib-gitloginfo](https://github.com/TYPO3-Documentation/sphinxcontrib-gitloginfo). And our solution is already active. For example, at the bottom of the ["TYPO3 Explained"](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/) pages you find the "Last updated ..." line with a link to the corresponding commit:
![image](https://user-images.githubusercontent.com/307057/86826561-34644980-c091-11ea-9abc-c7502362aa85.png)

And here is the mentioned [git-restore-mtime-modified.py](https://raw.githubusercontent.com/marble/Toolchain_RenderDocumentation/master/16-Convert-and-fix-and-check/git-restore-mtime/git-restore-mtime-modified.py). I "hacked" the original `git-restore-mtime` script because it almost did what I needed.

**Comment by mgeier** [comment]
Thanks for the update!

> Main problem is efficiency, as it takes to many Git calls.

That's a fair point.

Does your solution now use only one Git call to get all the information for the whole repository at once?

**Comment by mgeier** [comment]
I've added your extension to my README: #15.

**Comment by mgeier** [comment]
I've just created a PR that tries to reduce the number of calls to `git`, similar to how `git-restore-mtime` does it (but included in the Sphinx extension, not as a separate script): #25.

I don't know yet whether that leads to the expected runtime reduction, but I hope so.

**Comment by mgeier** [comment]
> I don't know yet whether that leads to the expected runtime reduction, but I hope so.

I've tried it on the NumPy docs, and it definitely works, all `git` calls are done within a few seconds.

I've also just made a new release, so the new, more efficient version is already available from PyPI.
