### ISSUE TITLE
Is there any way to detect if this extension is enabled?

### ISSUE THREAD

**Issue by pradyunsg** [mgeier/sphinx-last-updated-by-git#34]
Hiya! 👋🏽 

I'm working on a new theme and I'd like to ship a clean integration with this extension in that theme. The way that would work is that the "last_updated" content would be placed in a different location, if this extension is enabled (as part of a "article footer" instead of the "site footer").

For doing something like that in the theme's templates/Python code, it needs some way to detect that this extension is enabled and being used. Is there any way, that you know of, for detecting this?

x-ref: https://github.com/pradyunsg/lutra/issues/10

**Comment by mgeier** [comment]
I'm not aware of an obvious way to check this from templates. The idea of this extension is that it just fills already existing variables with meaningful values. So there are no additional variables that could be detected.

The only information that could be detected is the change in the `metatags` variable. You could parse that for `article:modified_time`. I don't know if that would even work, but it would certainly be brittle.

https://github.com/jdillard/sphinx-gitstamp uses a different approach, which might be easier to detect from a template.

In a Sphinx extension this should be easy to detect, but I guess that's not what you are looking for?

**Comment by pradyunsg** [comment]
Themes are also Sphinx extensions, so I'd be fine with trying to detect this stuff from an extension as well. :)

How would I do that though?

**Comment by pradyunsg** [comment]
> https://github.com/jdillard/sphinx-gitstamp uses a different approach, which might be easier to detect from a template.

It would be, and I might actually end up using that instead! Thanks for the pointer! :)

**Comment by mgeier** [comment]
> Themes are also Sphinx extensions

Well, that's not quite true.

Themes *can be* extensions if they choose to provide a Python module that has a toplevel `setup()` function with the right signature. They can also define a `sphinx.html_themes` entry point, which makes them easier to use for those people who want/can install the module.

But all this is completely optional, a Sphinx theme doesn't have to contain any Python code at all.

For my own Sphinx theme I have made sure that it is usable without restrictions even when not installed as a module, see the "Alternative Usage" box at the bottom of https://insipid-sphinx-theme.readthedocs.io/usage.html.

I think it's a pity that most of the popular "modern" Sphinx themes cannot be used like this.

> How would I do that though?

I guess you could define a `config-inited` callback that checks for `'sphinx_last_updated_by_git' in config.extensions`. I assume this will not cover extensions added by `setup_extension()`, buth there might be a work-around for that.

**Comment by pradyunsg** [comment]
> But all this is completely optional, a Sphinx theme doesn't have to contain any Python code at all.

Indeed, and I stand corrected!

> I think it's a pity that most of the popular "modern" Sphinx themes cannot be used like this.

That's fair, nad I can certainly see arguments against the you-need-python approach. I guess, hey, that's why diversity in the ecosystem is a good thing! :)

> checks for `'sphinx_last_updated_by_git' in config.extensions`.

Ah, okie! I think `setup_extension` would be something I'd like to cover, but I guess I'll poke around in Sphinx's code to see if I can find something. :)

**Comment by pradyunsg** [comment]
Alright, I think I have answers to my questions here. I really appreciate you taking the time to chat with me here @mgeier! ^.^

**Comment by mgeier** [comment]
> that's why diversity in the ecosystem is a good thing! :)

Yes, I very much agree.

Nice chatting with you, see you around.
