### ISSUE TITLE
Problems with signed commits

### ISSUE THREAD

**Issue by alainwolf** [mgeier/sphinx-last-updated-by-git#36]
Hi, 

My commits are PGP signed.

HTML building failed with:

```
getting Git timestamps for source files... [  3%] ~/src/myProject/SubDir                                                 
Extension error (sphinx_last_updated_by_git):
Handler <function _env_updated at 0x7f928d993040> for event 'env-updated' threw an exception (exception: unexpected git output in ~/src/myProject/SubDir: b'gpg: Signature made So 17 Apr 2022 19:44:16 CEST\n')
make: *** [Makefile:57: html] Error 2
```

###  Workaround:

`git config log.showSignature false`

**Comment by mgeier** [comment]
Thanks for this report.

It seems like showing the signature is disabled by default, so I guess you have it enabled via some config file?

Either way, this should of course not disturb this Sphinx extension.

Can you please try if #37 works for you?
