### ISSUE TITLE
Not working as expected for older projects using the PyData theme

### ISSUE THREAD

**Issue by agriyakhetarpal** [mgeier/sphinx-last-updated-by-git#54]
_I think other themes might be affected too, such as the PyData theme – I have not been able to make this work, neither locally nor on readthedocs (https://github.com/pybamm-team/PyBaMM/pull/3089). @mgeier could you please help investigate this? Here is a link to the [PR build](https://pybamm--3089.org.readthedocs.build/en/3089/index.html) and the [build logs](https://readthedocs.org/projects/pybamm/builds/21192279/). I did bump up the `Sphinx` version to `>= 6` in `docs/requirements.txt` (it was `>=1.5` earlier)._

_However, I can see that other projects have been able to make this extension work with the same theme, maybe this is an issue with our configuration? It is almost similar to others' configurations – so I don't see any conflicts. Or, is it because they are newer projects unlike ours (i.e., post-October 2020) and we have to request the aforementioned feature flag(s) in this thread from readthedocs?_

**Originally posted by @agriyakhetarpal in https://github.com/mgeier/sphinx-last-updated-by-git/issues/1#issuecomment-1616701207**

**Comment by agriyakhetarpal** [comment]
### Minimal reproducible example

```python
# in docs/conf.py

extensions = [
...
"sphinx_last_updated_by_git",
]

html_theme = "pydata_sphinx_theme"

# set by default by either the theme or by Sphinx, not sure if helps
html_last_updated_fmt = "%b %d, %Y"
```
Here is a link to the [full `conf.py` file](https://github.com/pybamm-team/PyBaMM/blob/783d9427bfd3813f429fe7829772e58649a68daf/docs/conf.py) for more configuration values. The project was hosted on readthedocs before October 2020.

### Relevant logs

The PR build and the build logs for readthedocs are in the issue comment above. I do not see any logs relevant to `sphinx-last-updated-by-git` locally

Command-line information via `pip`:
```
$ pip show sphinx-last-updated-by-git                                                      
Name: sphinx-last-updated-by-git
Version: 0.3.5
Summary: Get the "last updated" time for each Sphinx page from Git
Home-page: https://github.com/mgeier/sphinx-last-updated-by-git/
Author: Matthias Geier
Author-email: Matthias.Geier@gmail.com
License: BSD-2-Clause
Location: .nox/docs/lib/python3.11/site-packages
Requires: sphinx
Required-by: 
```

Let me know if I need to post any more information or logs, @mgeier. Thanks a lot!

**Comment by agriyakhetarpal** [comment]
I seem to have fixed it by manually adding the `"last-updated"` value to the footer options of the theme. Thanks for your time, I shall be closing this as the issue was resolved.

**Comment by mgeier** [comment]
Great to hear that it works now!

If somebody else stumbles upon this, the "last updated" information can be enabled in the PyData theme by using something like this in `conf.py`:

```python
html_theme_options = {
    "footer_start": [
        "copyright",
        "sphinx-version",
        "last-updated",
    ],
}
```

Alternatively, `"footer_end"` can be used.

For more options, see https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html#layout-footer

-----

There was also an unrelated problem about "shallow clones", where many warnings like this were shown:

    WARNING: Git clone too shallow

This can be fixed by updating the `.readthedocs.yml` file (see #55):

```yaml
version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
```
