### ISSUE TITLE
Doesn't work on the production websites when using with GitHub pages

### ISSUE THREAD

**Issue by xames3** [mgeier/sphinx-last-updated-by-git#56]
I configured the extension and deployed it. It works fine on the local builds and gives proper results. But when I pushed by changes on GitHub, the GitHub actions workflow was giving warning and failing the build because of the shallow depth as mentioned in the README. So to patch the error and failing builds, I added `suppress_warnings = ["git.too_shallow"]` in my `conf.py` file. The build was successful but the deployed pages didn't show the last updated footer as it was showing on my local build. Not sure why.

[This](https://xames3.github.io/learn/) is where it is not rendering. Please check the footer.

**Comment by mgeier** [comment]
Using `suppress_warnings` doesn't fix anything, it just silences the warning. The generated HTML files are unchanged.

To fix the problem, you'll have to somehow avoid the "shallow clone". I guess you can do that by adding something like `fetch-depth: 0` to `actions/checkout`. But I haven't tried that yet.

Once you found a way to make this work, please let me know, then I can add it to the README. Or feel free to make a PR with the updated documentation!

**Comment by n-peugnet** [comment]
> To fix the problem, you'll have to somehow avoid the "shallow clone". I guess you can do that by adding something like `fetch-depth: 0` to `actions/checkout`. But I haven't tried that yet.

This is exactly how I dit it and it is working as exepected: https://github.com/club-1/docs/blob/37415ac86dd3499d3eebcca48ba73aa2408409f0/.github/workflows/deploy.yml#L15-L18

**Comment by mgeier** [comment]
I think this has been clarified in the README and can be closed.

If something is still unclear, please let me know!
