### ISSUE TITLE
Is listing last modified pages possible?

### ISSUE THREAD

**Issue by alperyazar** [mgeier/sphinx-last-updated-by-git#65]
First of all, I would like to thank all the developers for this beautiful plugin.

I want to list the last changed pages with their links on one page of the document I created, for example, 10 most recently updated pages. For example, with the [todo plugin](https://www.sphinx-doc.org/en/master/usage/extensions/todo.html), when a `todolist` directive is used, all todos in the project are listed.

Is there a similar feature for this plugin (I couldn't see it in the documentation)? Or can it be added?

Thanks.

**Comment by mgeier** [comment]
> Is there a similar feature for this plugin (I couldn't see it in the documentation)?

No.

> Or can it be added?

Yes, I think so.

The time stamps of all source documents are available in `app.env.git_last_updated`.
You would only have to sort the entries and create the list of links.

**Comment by alperyazar** [comment]
Thank you very much. I will give a try.
