### ISSUE TITLE
Dates are incorrect when building the docs in GitLab

### ISSUE THREAD

**Issue by theletterf** [mgeier/sphinx-last-updated-by-git#76]
Hi there!

I'm trying to get accurate timestamps in the docs. We build them in GitLab; I set CICD to always perform full clones, so the entire git history is history is available. Nonetheless, dates always span a week time at most, so they're false.

I've read somewhere that `git-restore-mtime` might solve the issue? I don't see how, though. Do you know what else could be at play here?

We use Sphinx 5.1.1. 

Thanks!

**Comment by mgeier** [comment]
Did you read the last bullet point in the README file?

**Comment by theletterf** [comment]
:) I have now. I'm not sure we'll be able to upgrade. I'll try. Perhaps we'll downgrade... I'll report back.

**Comment by theletterf** [comment]
Seems like that did it. Thanks!
